# Generated by Django 4.1.1 on 2023-04-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpttextresponse', models.FileField(upload_to='')),
                ('userId', models.CharField(blank=True, max_length=100, null=True)),
                ('usermsg', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('salesProduct', models.CharField(blank=True, max_length=100, null=True)),
                ('salesRepcompany', models.CharField(blank=True, max_length=100, null=True)),
                ('salesRepPosition', models.CharField(blank=True, max_length=100, null=True)),
                ('generate', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('numberOfInquisitionQuestions', models.IntegerField(blank=True, null=True)),
                ('numberOfObjectionQuestions', models.IntegerField(blank=True, null=True)),
                ('prospectfor', models.CharField(blank=True, max_length=100, null=True)),
                ('followUp', models.BooleanField(default=False)),
                ('current_question_index', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='salesRepCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('followUp', models.BooleanField(default=False)),
                ('current_question_index', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionssalesRepCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('salesRepcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.prospectcompany')),
            ],
        ),
    ]
