# Generated by Django 4.1.1 on 2023-04-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_questionssalesrepcompany_salesrepcompany_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectcompany',
            name='current_question_index',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
