# Generated by Django 4.1.1 on 2023-04-26 03:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_customersupportpersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersupportpersona',
            name='queues',
            field=jsonfield.fields.JSONField(default={'customer_queue': [], 'executive_queue': []}),
        ),
    ]
