# Generated by Django 4.1.1 on 2023-05-05 15:11

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_customersupportpersona_id_alter_products_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', jsonfield.fields.JSONField(default={'timestamps': []})),
            ],
        ),
    ]
