# Generated by Django 4.1.1 on 2023-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamps',
            name='title',
            field=models.TextField(default='TimeStamps'),
        ),
    ]
