# Generated by Django 3.1.4 on 2023-05-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_videopath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopath',
            old_name='videpath',
            new_name='videopath',
        ),
    ]
