# Generated by Django 4.1.1 on 2023-05-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20230506_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerSupportPersona',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.RemoveField(
            model_name='questionssalesrepcompany',
            name='salesRepcompany',
        ),
        migrations.DeleteModel(
            name='salesRepCompany',
        ),
        migrations.DeleteModel(
            name='TimeStamps',
        ),
        migrations.DeleteModel(
            name='VideoPath',
        ),
        migrations.DeleteModel(
            name='ProspectCompany',
        ),
        migrations.DeleteModel(
            name='QuestionssalesRepCompany',
        ),
    ]
