# Generated by Django 5.0.3 on 2024-04-02 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0014_delete_customersupportpersona_delete_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('is_fake', models.BooleanField(default=False)),
            ],
        ),
    ]
